name: Feature request
description: Suggest a feature to be featured in your feature-filled feature
labels: ["type: enhancement"]
assignees: ["Commenter25"]

body:
  - type: markdown
    attributes:
      value: "Thank you for creating a report! Please be sure to add a short and simple title above, with no tagging like [FEATURE]."

  - type: dropdown
    id: style
    attributes:
      label: "Which style is this issue about?"
      options:
        - Dark Example
        - raevision
        - Transparent Standalone Images
        - Xenia as Steam Icon
    validations:
      required: true

  - type: textarea
    id: whathapen
    attributes:
      label: "What's your request?"
      description: "Please provide a clear and concise description of what you want to happen. If it's related to another issue, you should mention that. Add any other context or screenshots that may be helpful."
      placeholder: Say what you want to see!
    validations:
      required: true

  - type: textarea
    id: ideas
    attributes:
      label: "What's some potential ideas or alternatives for this to work?"
      description: "If you can, provide a clear and concise description of how you think this could work best, as well as any alternative solutions or features you've considered. **This is optional, do not feel pressured to think of something!**"
      placeholder: Say what will let you see it!
